document.addEventListener('DOMContentLoaded', async () => {
    const reportsContainer = document.getElementById('reports-container');
    const currentPriceEl = document.getElementById('current-price');
    const lastUpdateEl = document.getElementById('last-update');
    const errorBox = document.getElementById('error-box');

    try {
        // Retrieve data generated by background.js
        chrome.storage.session.get(['fetih_reports', 'fetih_current_price', 'fetih_last_update'], (data) => {
            if (chrome.runtime.lastError) {
                showError('Veri okunamadı: ' + chrome.runtime.lastError.message);
                return;
            }

            if (data.fetih_current_price) {
                currentPriceEl.textContent = new Intl.NumberFormat('tr-TR', { minimumFractionDigits: 2 }).format(data.fetih_current_price);
            }

            if (data.fetih_last_update) {
                const date = new Date(data.fetih_last_update);
                lastUpdateEl.textContent = date.toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' });
            }

            if (data.fetih_reports && data.fetih_reports.length > 0) {
                renderReports(data.fetih_reports);
            } else {
                reportsContainer.innerHTML = `
                    <div class="loading-state">
                        <span class="material-symbols-outlined spin">hourglass_top</span>
                        <p>Henüz yeterli veri birikmedi. Lütfen bekleyin.</p>
                    </div>`;
            }
        });

    } catch (err) {
        showError('Beklenmeyen bir hata oluştu: ' + err.message);
    }

    function renderReports(reports) {
        reportsContainer.innerHTML = '';
        reports.forEach(report => {
            let icon = 'monitoring';
            let title = 'Genel Rapor';
            
            if (report.type === 'iscilik') {
                icon = 'warning';
                title = 'İşçilik (Premium) Uyarı';
            } else if (report.type === 'gunluk') {
                icon = 'trending_up';
                title = 'Günlük Analiz';
                if (report.msg.includes('düşüş') || report.msg.includes('geri çekilme')) {
                    icon = 'trending_down';
                } else if (report.msg.includes('stabil')) {
                    icon = 'horizontal_rule';
                }
            }

            const card = document.createElement('div');
            card.className = 'report-card';
            card.innerHTML = `
                <div class="report-header">
                    <span class="material-symbols-outlined report-icon">${icon}</span>
                    <span class="report-title">${title}</span>
                </div>
                <p class="report-text">${highlightText(report.msg)}</p>
            `;
            reportsContainer.appendChild(card);
        });
    }

    function highlightText(text) {
        const GOLD = '#e9c176';
        let s = text.replace(/([+-]?\d+[,.]?\d*%)(?![\w])/g, `<span style="color:${GOLD};font-weight:700">$1</span>`);
        s = s.replace(/([+-]?\d+[,.]?\d*\sTL)/g, `<span style="color:${GOLD};font-weight:700">$1</span>`);
        return s;
    }

    function showError(msg) {
        errorBox.textContent = msg;
        errorBox.classList.remove('hidden');
        reportsContainer.innerHTML = '<p style="color:var(--outline); font-size:12px; text-align:center;">Veri yüklenemedi.</p>';
        document.getElementById('status-dot').classList.add('offline');
    }
});
